trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  node_version: 18.x
  acrName: netflixcloneimage
  imageName: netflix-clone
  namespace: netflix-prod

steps:

# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

# Build frontend
- script: |
    cd frontend
    npm install
    npm run build
  displayName: Build frontend

# Attach frontend to backend
- script: |
    rm -rf backend/public
    mkdir -p backend/public
    cp -r frontend/dist/* backend/public/
  displayName: Attach frontend to backend

# Install backend dependencies
- script: |
    cd backend
    npm install --omit=dev
  displayName: Install backend dependencies

# Remove env files
- script: rm -f backend/.env
  displayName: Remove env files

# Build & push Docker image to ACR
- task: Docker@2
  displayName: Build and push image to ACR
  inputs:
    command: buildAndPush
    containerRegistry: $(acrName)
    repository: $(imageName)
    Dockerfile: Dockerfile-AzureDevOps
    buildContext: .
    tags: |
      latest

# AKS login
- task: Kubernetes@1
  displayName: AKS login
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: azure-connection
    azureResourceGroup: netflix-clone-deploy
    kubernetesCluster: test01
    command: login

# Create namespace (idempotent)
- script: |
    kubectl get ns $(namespace) || kubectl create ns $(namespace)
  displayName: Ensure namespace exists

# Apply manifests
- script: |
    kubectl apply -f k8s/azure/deployment.yaml -n $(namespace)
    kubectl apply -f k8s/azure/service.yaml -n $(namespace)
  displayName: Apply manifests

# Force deployment to use latest image
- script: |
    kubectl set image deployment/netflix-clone \
      netflix-clone=$(acrName).azurecr.io/$(imageName):latest \
      -n $(namespace)
  displayName: Update deployment image to latest

# Verify rollout
- script: |
    kubectl rollout status deployment/netflix-clone -n $(namespace)
  displayName: Verify deployment
