trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  node_version: 18.x

steps:
- task: NodeTool@0
  inputs:
    versionSpec: $(node_version)

# Build frontend
- script: |
    cd frontend
    npm install
    npm run build
  displayName: Build frontend

# Attach frontend build to backend
- script: |
    rm -rf backend/public
    mkdir -p backend/public
    cp -r frontend/dist/* backend/public/
  displayName: Attach frontend to backend

# Install backend dependencies
- script: |
    cd backend
    npm install --production
  displayName: Install backend dependencies

# Remove accidental env files
- script: |
    rm -f backend/.env
  displayName: Ensure no env file is deployed

# Package application
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: backend
    includeRootFolder: false
    archiveType: zip
    archiveFile: $(Build.ArtifactStagingDirectory)/app.zip
    replaceExistingArchive: true

# Deploy to App Service
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'azure-connection'
    appType: webAppLinux
    appName: 'netflix-clone'
    package: $(Build.ArtifactStagingDirectory)/app.zip
