# ===== Service =====
apiVersion: v1
kind: Service
metadata:
  name: netflix-clone-svc
spec:
  selector:
    app: netflix
  ports:
    - protocol: TCP
      port: 80         # service port (used inside cluster)
      targetPort: 5000 # forwards to containerPort
      nodePort: 30007  # optional; access via <NodeIP>:30007
  type: NodePort
